GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJMeXNhbnVyIiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJpYXQiOjE3MzM2NzY4MDMsImV4cCI6MTczMzY3NjgxOH0.2I8JEtWCsJlbMGumrlN_X2yuhdIy6i7Xcob5YQnBiTs


###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Lysanur 2",
    "email": "email2@gmail.com",
    "password": "123456",
    "confPassword": "123457"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "123456"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout
